#服务器配置
server:
  port: 6680

#Spring配置
spring:

  #应用配置
  application:
    name: ftcli-ai-server

  config:
    import: optional:classpath:application-local.yaml

  #SQLite数据源配置
  datasource:
    url: jdbc:sqlite:${FTCLI_DB_PATH:${user.home}/.ftcli/ftcli.db}
    driver-class-name: org.sqlite.JDBC

#LangChain4j配置
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      model-name: deepseek-chat
      temperature: 0.7
      timeout: 30s
      log-requests: false
      log-responses: false
    streaming-chat-model:
      base-url: https://api.deepseek.com
      model-name: deepseek-chat
      temperature: 0.7
      timeout: 30s
      log-requests: false
      log-responses: false

#日志配置
logging:
  level:
    root: INFO  #只输出警告及以上级别

#swagger配置
swagger:
  enabled: true
  title: 'ftcli API'
  description: "ftcli API"
  version: '1.0'
  base-package: com.ftc.ftcli

#AI配置
ai:
  chat-memory:
    max-tokens: 95000
    token-estimator-model: gpt-4o
  embedding:
    model:
      zhipu:
        model-name: embedding-3
    store:
      chroma:
        url: ${CHROMA_URL:http://localhost:8000}
        tenant: langchain4j
        database: langchain4j_db
        collection: langchain4j_coll
    ingestor:
      max-segment-size: 2000
      overlap: 200
      token-estimator-model: gpt-4o
  rag:
    web-search:
      max-results: 5
    content-retriever:
      max-results: 5
      min-score: 0.5
    rerank:
      model: jina-reranker-v3
      max-results: 3
      min-score: 0.08