#服务器配置
server:
  port: 6680

#Spring配置
spring:

  #应用配置
  application:
    name: ftcli

  #Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 1
      jedis:
        pool:
          max-active: 150
          max-wait: 100
          max-idle: 100
          min-idle: 50
      timeout: 5000ms

  #SQLite数据源配置
  datasource:
    url: jdbc:sqlite:C:/Users/Administrator/project/java/ftcli/data/ftcli.db
    driver-class-name: org.sqlite.JDBC

#LangChain4j配置
langchain4j:
  open-ai:
    chat-model:
      api-key: xxx
      base-url: https://api.deepseek.com
      model-name: deepseek-chat
      temperature: 0.7
      timeout: 30s
      log-requests: true
      log-responses: true
    streaming-chat-model:
      api-key: xxx
      base-url: https://api.deepseek.com
      model-name: deepseek-chat
      temperature: 0.7
      timeout: 30s
      log-requests: true
      log-responses: true

#日志配置
logging:
  level:
    root: INFO  #只输出警告及以上级别

#swagger配置
swagger:
  enabled: true
  title: 'ftcli API'
  description: "ftcli API"
  version: '1.0'
  base-package: com.ftc.ftcli

#AI配置
ai:
  chat-memory:
    max-tokens: 95000
    token-estimator-model: gpt-4o
  embedding:
    model:
      zhipu:
        api-key: xxx
        model-name: embedding-3
    store:
      chroma:
        url: http://localhost:8000
        tenant: langchain4j
        database: langchain4j_db
        collection: langchain4j_coll
  rag:
    ingestor:
      max-segment-size: 1500
      overlap: 200
      token-estimator-model: gpt-4o
    web-search:
      api-key: xxx